// The single source of truth for the boats column mapping, shared by the seed
// generator (gen-seed.mjs → SQL) and the row transform (gen-rows.mjs → JSON for
// PostgREST). Keep in lockstep with supabase/migrations/*_initial_schema.sql and
// the rowToBoat adapter in src/lib/data.ts.
//
// [ snake_case column, camelCase JSON key, kind ]
//   kind: text | num | arr (text[]) | json (jsonb)
export const COLUMNS = [
  ["id", "id", "text"],
  ["name", "name", "text"],
  ["builder", "builder", "text"],
  ["designer", "designer", "text"],
  ["color", "color", "text"],
  ["years", "years", "text"],
  ["material", "material", "text"],
  ["category", "category", "text"],
  ["cockpit_type", "cockpitType", "text"],
  ["loa", "loa", "text"],
  ["lwl", "lwl", "text"],
  ["beam", "beam", "text"],
  ["draft_min", "draftMin", "text"],
  ["draft_max", "draftMax", "text"],
  ["displacement", "displacement", "text"],
  ["ballast", "ballast", "text"],
  ["ballast_ratio", "ballastRatio", "text"],
  ["sail_area", "sailArea", "text"],
  ["air_draft", "airDraft", "text"],
  ["engine", "engine", "text"],
  ["drive", "drive", "text"],
  ["cabins", "cabins", "text"],
  ["keel", "keel", "text"],
  ["cockpit", "cockpit", "text"],
  ["fuel", "fuel", "text"],
  ["water", "water", "text"],
  ["loa_n", "loaN", "num"],
  ["lwl_ft", "lwlFt", "num"],
  ["beam_ft", "beamFt", "num"],
  ["disp_lb", "dispLb", "num"],
  ["draft_min_n", "draftMinN", "num"],
  ["sad", "sad", "text"],
  ["dl", "dl", "text"],
  ["fuel_n", "fuelN", "num"],
  ["water_n", "waterN", "num"],
  ["engine_hp", "engineHp", "num"],
  ["price_min_usd", "priceMinUSD", "num"],
  ["price_max_usd", "priceMaxUSD", "num"],
  ["budget", "budget", "text"],
  ["budget_n", "budgetN", "num"],
  ["best_for", "bestFor", "text"],
  ["protection_text", "protectionText", "text"],
  ["rig", "rig", "text"],
  ["handling_text", "handlingText", "text"],
  ["engine_workshop", "engineWorkshop", "text"],
  ["systems", "systems", "text"],
  ["storage_text", "storageText", "text"],
  ["range_text", "rangeText", "text"],
  ["accommodation", "accommodation", "text"],
  ["high_lat_text", "highLatText", "text"],
  ["tropical_text", "tropicalText", "text"],
  ["price_text", "priceText", "text"],
  ["price_new", "priceNew", "text"],
  ["price_used", "priceUsed", "text"],
  ["budget_text", "budgetText", "text"],
  ["notable", "notable", "text"],
  ["scores", "scores", "json"],
  ["tags", "tags", "arr"],
  ["fun", "fun", "arr"],
  ["price_examples", "priceExamples", "arr"],
  ["sources", "sources", "json"],
  ["youtube", "youtube", "json"],
  ["pros", "pros", "arr"],
  ["cons", "cons", "arr"],
  ["awards", "awards", "arr"],
  ["endorsements", "endorsements", "json"],
  ["badge", "badge", "text"],
  ["own", "own", "json"],
];
