// Generate supabase/seed.sql from data/boats.json.
//
// Emits one idempotent `insert ... on conflict (id) do update` so the file
// doubles as a re-runnable refresh tool: applied by `supabase db reset`
// locally, or run against the cloud DB once after the schema migration.
//
//   node scripts/gen-seed.mjs   →   supabase/seed.sql
//
// Column order and snake_case names mirror the schema migration and the
// rowToBoat adapter in src/lib/data.ts. If the Boat shape changes, update the
// COLUMNS table below in lockstep with both.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { COLUMNS } from "./columns.mjs";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const boats = JSON.parse(readFileSync(resolve(root, "data/boats.json"), "utf8"));

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'"; // SQL string literal

function cell(value, kind) {
  if (value === null || value === undefined) return "null";
  switch (kind) {
    case "num":
      if (typeof value !== "number" || Number.isNaN(value))
        throw new Error(`expected number, got ${JSON.stringify(value)}`);
      return String(value);
    case "arr": {
      if (!Array.isArray(value)) throw new Error(`expected array`);
      if (value.length === 0) return "array[]::text[]";
      return "array[" + value.map((x) => q(x)).join(", ") + "]::text[]";
    }
    case "json":
      return q(JSON.stringify(value)) + "::jsonb";
    case "text":
    default:
      return q(value);
  }
}

const cols = COLUMNS.map(([c]) => c);
const rows = boats.map((b, i) => {
  try {
    return "  (" + COLUMNS.map(([, key, kind]) => cell(b[key], kind)).join(", ") + ")";
  } catch (e) {
    throw new Error(`boat[${i}] id=${b.id}: ${e.message}`);
  }
});

// Upsert: on conflict, refresh every data column from the new values and bump
// updated_at. id is the conflict target, so it is excluded from the SET list.
const setClause = cols
  .filter((c) => c !== "id")
  .map((c) => `  ${c} = excluded.${c}`)
  .concat("  updated_at = now()")
  .join(",\n");

const sql = `-- Seed data for public.boats — generated by scripts/gen-seed.mjs from
-- data/boats.json. Do not edit by hand; regenerate after changing the fixture.
-- Idempotent: re-running refreshes existing rows (upsert on id).

insert into public.boats (
${cols.map((c) => "  " + c).join(",\n")}
) values
${rows.join(",\n")}
on conflict (id) do update set
${setClause};
`;

writeFileSync(resolve(root, "supabase/seed.sql"), sql);
console.log(`Wrote supabase/seed.sql: ${boats.length} boats, ${cols.length} columns each.`);
